config/routes.rb
ForumBetty::Application.routes.draw do

  resources :posts

  resources :topics

  resources :forums

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "forums#index"

end

app/models/forum.rb
class Forum < ActiveRecord::Base

  has_many :topics, :dependent => :destroy

  def most_recent_post
    topic = Topic.first(:order => 'last_post_at DESC', :conditions => ['forum_id = ?', self.id])
    return topic
  end

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :admin_required, :except => [:index, :show] 
  
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to @forum, :notice => "Successfully created forum."
    else
      render :action => 'new'
    end
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def update
    @forum = Forum.find(params[:id])
    if @forum.update_attributes(params[:forum])
      redirect_to @forum, :notice  => "Successfully updated forum."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to forums_url, :notice => "Successfully destroyed forum."
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for @forum do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/forums/edit.html.erb
<% title "Edit Forum" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @forum %> |
  <%= link_to "View All", forums_path %>
</p>

app/views/forums/index.html.erb
<% title "Forums" %>

<table>
  <tr>
    <th width="70%">Forum</th>
    <th width="30%">Last Post</th>
  </tr>
  <% for forum in @forums %>
    <tr>
      <td><h4><%= link_to forum.name, forum_path(forum.id) %></h4>
        <small><%= forum.topics.count %> topics </small><br />
        <%= forum.description %></td>
      <td class="right">
        <% if forum.most_recent_post %>
          <%= distance_of_time_in_words_to_now forum.most_recent_post.last_post_at %> ago by
          <%= link_to forum.most_recent_post.user.username, "/users/#{forum.most_recent_post.last_poster_id}" %>
        <% else %>
          no posts
        <% end %>
      </td>
      <% if admin? %>
        <td><%= link_to "Edit", edit_forum_path(forum) %></td>
      <% end %>
      <% if admin? %>
        <td><%= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><% if admin? %><%= link_to "New Forum", new_forum_path %><% end %></p>

app/views/forums/new.html.erb
<% title "New Forum" %>

<%= render 'form' %>

<p><%= link_to "Back to List", forums_path %></p>

app/views/forums/show.html.erb
<% title @forum.name %>

<table>
  <tr>
    <th width="60%">Topic Title</th>
    <th width="10%">Replies</th>
    <th width="30%">Last Post</th>
  </tr>
  <% for topic in @forum.topics %>
    <tr>
      <td><%= link_to topic.name, topic_path(topic.id) %>
      <td><%= topic.posts.count %></td>
      <td class="right">
        <%= distance_of_time_in_words_to_now topic.last_post_at %> ago by 
        <%= link_to topic.user.username, "/users/#{topic.last_poster_id}" %>
      </td>
      <% if admin? %> <td><%= link_to "Destroy", topic, :confirm => 'Are you sure?', :method => :delete %></td> <% end %> 
    </tr>
  <% end %>
</table>

<p><% if logged_in? %><%= link_to "New Topic", "/topics/new?forum=#{@forum.id}" %><% end %></p>