config/routes.rb
ForumBetty::Application.routes.draw do

  resources :posts

  resources :topics

  resources :forums

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "forums#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  belongs_to :forum
  belongs_to :user 
  has_many :posts, :dependent => :destroy
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :login_required, :except => [:index, :show] 
  before_filter :admin_required, :only => :destroy 
  
  def show
    @topic = Topic.find(params[:id])
  end

  def new
    #@topic = Topic.new(:name => params[:topic][:name], :last_poster_id => current_user.id, :last_post_at => Time.now, :forum_id => params[:forum_id], :user_id => current_user.id)
    @topic = Topic.new
  end

  def create

    @topic = Topic.new(:name => params[:topic][:name], :last_poster_id => current_user.id, :last_post_at => Time.now, :forum_id => params[:topic][:forum_id], :user_id => current_user.id)

    if @topic.save
      @post = Post.new(:content => params[:post][:content], :topic_id => @topic.id, :user_id => current_user.id)
      
      if @post.save
        flash[:notice] = "Successfully created topic."
        redirect_to "/forums/#{@topic.forum_id}"
      else
        redirect :action => 'new'
      end
    else
      render :action => 'new'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to "/forums/#{@topic.forum_id}" 
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <%= f.error_messages %>
  <% if params[:forum] %><input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum] %>" /><% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <% if @post %>
      <textarea name="post[content]" cols="80" rows="20"><%= @post.content %></textarea>
    <% else %>
      <textarea name="post[content]" cols="80" rows="20"></textarea>
    <% end %>
  </p>
 
  <p><%= f.submit "Create"%></p>
<% end %>

app/views/topics/edit.html.erb
<% title "Edit Topic" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @topic %> |
  <%= link_to "View All", topics_path %>
</p>

app/views/topics/index.html.erb
<% title "Topics" %>

<table>
  <tr>
    <th>Name</th>
    <th>Last Poster</th>
    <th>Last Post At</th>
  </tr>
  <% for topic in @topics %>
    <tr>
      <td><%= topic.name %></td>
      <td><%= topic.last_poster_id %></td>
      <td><%= topic.last_post_at %></td>
      <td><%= link_to "Show", topic %></td>
      <td><%= link_to "Edit", edit_topic_path(topic) %></td>
      <td><%= link_to "Destroy", topic, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Topic", new_topic_path %></p>

app/views/topics/new.html.erb
<% title "New Topic" %>

<%= render 'form' %>

<p><%= link_to "Back to List", topics_path %></p>

app/views/topics/show.html.erb
<% title @topic.name %>

<% for post in @topic.posts %>
<div class="post">
  <span class="left">
    <%= link_to post.user.username, user_url(post.user) %>
    <br />
    <% link_to "Edit", edit_post_path(post) %>
    <br />
    <%= link_to "Delete", post, :confirm => 'Are you sure?', :method => :delete %>
  </span>
  <span class="right"><%= post.content %></span>
</div>
<% end %>

<p>
  <% if logged_in? %><%= link_to "Reply", "#{new_post_path}?topic=#{@topic.id}" %> |<% end %>
  <% if admin? %><%= link_to "Destroy Topic", @topic, :confirm => 'Are you sure?', :method => :delete %> |<% end %>
  <%= link_to "View All", forum_path(@topic.forum_id) %>
</p>